variables:
  - group: variables-macOS
  - name: isReleaseMode
    value: true
  - name: buildWin32
    value: false
  - name: buildWin64
    value: true
  - name: OBSLatestTag
    value: 26.1.2

trigger:
  branches:
    include:
      - master
      - main
  tags:
    include:
      - '*'

jobs:
- job: 'Build_Windows'
  pool:
    vmImage: 'windows-2019'
  variables:
    build_config: RelWithDebInfo
    DepsBasePath: 'D:\obsdependencies'
    DepsPath32: '$(DepsBasePath)\win32'
    DepsPath64: '$(DepsBasePath)\win64'
    QtBaseDir: 'D:\QtDep'
    QTDIR32: '$(QtBaseDir)\5.10.1\msvc2017'
    QTDIR64: '$(QtBaseDir)\5.10.1\msvc2017_64'
    OBSPath: 'D:\obs-studio'
  condition: or(eq(variables['buildWin32'], true), eq(variables['buildWin64'], true))
  steps:
    - checkout: self
      submodules: true

    - script: ./ci/windows/install-qt-win.cmd
      displayName: 'Install Qt'
      env:
        QtBaseDir: $(QtBaseDir)

    - task: Cache@2
      displayName: Restore cached OBS Studio dependencies
      inputs:
        key: 'obsdeps | "$(Agent.OS)"'
        path: $(DepsBasePath)

    - script: ./ci/windows/download-obs-deps.cmd
      displayName: 'Download OBS Studio dependencies'

    - task: Cache@2
      displayName: Restore cached OBS Studio builds
      inputs:
        key: 'obs "$(OBSLatestTag)" | obs-frontend-api-only | "$(Agent.OS)"'
        path: $(OBSPath)

    - script: ./ci/windows/prepare-obs-windows.cmd
      displayName: 'Checkout & CMake OBS Studio'
      env:
        build_config: $(build_config)
        DepsPath32: $(DepsPath32)
        DepsPath64: $(DepsPath64)
        QTDIR32: $(QTDIR32)
        QTDIR64: $(QTDIR64)
        OBSPath: $(OBSPath)
        OBSLatestTag: $(OBSLatestTag)
        buildWin32: $(buildWin32)
        buildWin64: $(buildWin64)

    - script: ./ci/windows/prepare-windows.cmd
      displayName: 'CMake Plugin'
      env:
        build_config: $(build_config)
        QTDIR32: $(QTDIR32)
        QTDIR64: $(QTDIR64)
        OBSPath: $(OBSPath)
        buildWin32: $(buildWin32)
        buildWin64: $(buildWin64)

    - task: MSBuild@1
      displayName: 'Build Plugin 32-bit'
      condition: eq(variables['buildWin32'], true)
      inputs:
        msbuildArguments: '/m /p:Configuration=$(build_config)'
        solution: '.\build32\main.sln'

    - task: MSBuild@1
      displayName: 'Build Plugin 64-bit'
      condition: eq(variables['buildWin64'], true)
      inputs:
        msbuildArguments: '/m /p:Configuration=$(build_config)'
        solution: '.\build64\main.sln'

    - script: ./ci/windows/package-windows.cmd
      displayName: 'Package Plugin'

    - task: PublishBuildArtifacts@1
      displayName: 'Upload package artifacts'
      inputs:
        pathtoPublish: './package'
        artifactName: 'windows_build'

- job: 'Build_Linux'
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
      BUILD_REASON: $(Build.Reason)
      BRANCH_SHORT_NAME: $(Build.SourceBranchName)
      BRANCH_FULL_NAME: $(Build.SourceBranch)
  steps:
    - checkout: self
      submodules: true

    - script: ./ci/linux/install-dependencies-ubuntu.sh
      displayName: 'Install dependencies'

    - script: ./ci/linux/build-ubuntu.sh
      displayName: 'Build Plugin'

    - script: ./ci/linux/package-ubuntu.sh
      displayName: 'Package Plugin'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: './package'
        artifactName: 'deb_build'

- job: 'Build_macOS'
  pool:
    vmImage: 'macos-10.14'
  steps:
    - checkout: self
      submodules: true

    - script: ./ci/macos/install-build-obs-macos.sh
      displayName: 'Build OBS'
      env:
        OBSLatestTag: $(OBSLatestTag)

    - script: ./ci/macos/build-macos.sh
      displayName: 'Build Plugin'

    - task: InstallAppleCertificate@2
      displayName: 'Install release signing certificates'
      inputs:
        certSecureFile: 'Certificates.p12'
        certPwd: $(secrets.macOS.certificatesImportPassword)

    - script: ./ci/macos/package-macos.sh
      displayName: 'Package Plugin'
      env:
        RELEASE_MODE: True
        CODE_SIGNING_IDENTITY: $(secrets.macOS.codeSigningIdentity)
        INSTALLER_SIGNING_IDENTITY: $(secrets.macOS.installerSigningIdentity)
        AC_USERNAME: $(secrets.macOS.notarization.username)
        AC_PASSWORD: $(secrets.macOS.notarization.password)
        AC_PROVIDER_SHORTNAME: $(secrets.macOS.notarization.providerShortName)

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: './release'
        artifactName: 'macos_build'
